### ISSUE TITLE
ERROR with LUA http

### ISSUE THREAD

**Issue by Niwla23** [archfan7411/discordmt#3]
~/.minetest/mods/discordmt/init.lua:108: attempt to index upvalue 'http' (a nil value)
getting this error! What am i doing wrong???? @archfan7411

**Comment by archfan7411** [comment]
You need to give the mod access to the HTTP API. Paste the following lines into your `minetest.conf`:
```
secure.enable_security = true
secure.trusted_mods = discordmt
```

**Comment by appgurueu** [comment]
@archfan7411 I suggest you to close the issue.

**Comment by archfan7411** [comment]
I'm just waiting for confirmation that this fixed their issue.

**Comment by Niwla23** [comment]
thanks, that worked

**Comment by Panquesito7** [comment]
> You need to give the mod access to the HTTP API. Paste the following lines into your `minetest.conf`:
> 
> ```
> secure.enable_security = true
> secure.trusted_mods = discordmt
> ```

@archfan7411, you probably want to set a note in `README.md`.
I don't see any instructions specifying to add those lines to your `minetest.conf`.
