### ISSUE TITLE
Relay timing out

### ISSUE THREAD

**Issue by PiMonkey14** [archfan7411/discordmt#4]
randomly someone on my server will send a msg from discord and it wont go ingame not sure if its doing the same when I send a msg from ingame to Discord but here is what debug.txt is reporting

`2019-11-16 16:56:48: ERROR[CurlFetch]: localhost:8080 not found (Timeout was reached) (response code 0)`
`2019-11-16 16:56:48: ERROR[CurlFetch]: localhost:8080 not found (Timeout was reached) (response code 0)`
`2019-11-16 16:56:49: ERROR[CurlFetch]: localhost:8080 not found (Timeout was reached) (response code 0)`

it sends that error 3 times and then gives up and the msg will not be sent
this has happonded a number of times and at random times

**Comment by archfan7411** [comment]
Interesting; from this and the error you provided in Discord it appears that the Python side is taking too long to respond to Minetest's requests. This really shouldn't happen unless the Python side is processing something very large (and even then this is unexpected.)

As an experiment, could you try using [this branch I just made](https://github.com/archfan7411/discordmt/tree/longer-timeout) which increases the request timeout to 30 seconds?

**Comment by archfan7411** [comment]
Also, as an afterthought, please also try upgrading `discord.py` (`pip install -U discord.py`)

**Comment by PiMonkey14** [comment]
kk will try it and let u know if this solves everything in 24-48 hours

**Comment by PiMonkey14** [comment]
not got anymore errors from the relay in the past 2 days and no msgs have been lost so I think u fixed it 
ty Archfan!
