### ISSUE TITLE
Missing command reference

### ISSUE THREAD

**Issue by Niwla23** [archfan7411/discordmt#5]
I cant find any refernece for the availabel commands

**Comment by archfan7411** [comment]
I'll add a help command in the next few days, but until then, here's a list:

`!status` - Shows the connected players, max_lag, MOTD, etc., equivalent to the `/status` command ingame. Can be used without logging in.

`!login <username> [password]` - Logs you into Minetest so you can run commands through Discord. This command should *only* be used in DMs with the bot.

`!cmd <command> [params]` - Runs a command from Discord, equivalent to running `/<command> [params]` ingame. Can be used in either the relay channel or DMs with the bot.

**Comment by archfan7411** [comment]
96c1346
