### ISSUE TITLE
What is the `port` doing?

### ISSUE THREAD

**Issue by Avyukt1** [archfan7411/discordmt#6]
![image](https://user-images.githubusercontent.com/65779812/104084528-d4cc3e00-526d-11eb-8732-a2b6fb46403a.png)

**Comment by PiMonkeyServers** [comment]
did you start the server.py script before starting the minetest server?

**Comment by Avyukt1** [comment]
Yes, do have I keep it executed or close the window?

**Comment by PiMonkeyServers** [comment]
> 
> 
> Yes I had started it, do have I keep it executed or close the window?

yes you need to keep it executed

**Comment by Avyukt1** [comment]
Oh thanks, its workings now!

**Comment by PiMonkeyServers** [comment]
glad to hear it
