### ISSUE TITLE
Offer a way to relay without needing to run a relay server

### ISSUE THREAD

**Issue by IITFA** [archfan7411/discordmt#8]
I am running my minetest server on a hosted server since I can't host from home. There is no way to run the relay server due to the configuration of the minetest host. This mod should be made to not require a relay server because when minetest grows, there will be many servers on hosted servers and they too will not have the ability to run a relay server.

If there is no way to do this via a mod without having the core on minetest altered, push for such alterations in the core of minetest so it is possible.

**Comment by archfan7411** [comment]
I do apologize for not seeing this sooner -

Discord's API is based on websockets, and it is currently impossible to maintain a websocket connection from within Minetest. As far as I can tell it would be a non-trivial engine change to implement such support.

I'm assuming that you're using a dedicated Minetest hosting service, as if you were hosting from a VPS then it should be trivial to get discordmt running.

Within the next few months I may be rolling out a free service where the relay bot is hosted by myself on a high quality VPS, with modifications so it can relay for many individual servers at once. That way, hosting your own relay server will no longer be strictly required, although always supported. The actual implementation remains to be seen.

If you have any more questions or suggestions, please feel free to re-open this thread!
